sudo: required
services:
  - docker

before_install:
  - docker build -t danielbender/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true danielbender/react-test npm test

after_success:
  - docker build -t danielbender/multi-client ./client
  - docker build -t danielbender/multi-nginx ./nginx
  - docker build -t danielbender/multi-server ./server
  - docker build -t danielbender/multi-client ./client
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Dockerhub
  - docker push danielbender/multi-client
  - docker push danielbender/multi-nginx
  - docker push danielbender/multi-server
  - docker push danielbender/multi-worker
